spring.application.name=order-service
server.port=8081

# RocketMQ name-server & producer group
#rocketmq.name-server=namesrv-1:9876;namesrv-2:9876;namesrv-3:9876
rocketmq.name-server=localhost:9876
rocketmq.producer.group=producer-group

# Docker Compose 生命周期管理
spring.docker.compose.lifecycle-management=start-only
# 显式指定停止时的动作为 docker compose down（彻底清理网络和容器）
#spring.docker.compose.stop.command=down

# 应用名称
dubbo.application.name=order-service

# Zookeeper 注册中心配置 (ID为 zk)
#dubbo.registries.zk.id=zk
#dubbo.registries.zk.protocol=zookeeper
#dubbo.registries.zk.address=192.168.5.22:2181

# Nacos 注册中心配置 (ID为 nacos)
dubbo.registries.nacos.id=nacos
dubbo.registries.nacos.protocol=nacos
dubbo.registries.nacos.address=192.168.5.22:8848

# 服务提供者向所有注册中心注册
dubbo.provider.register-mode=application
# 消费端启动时不强制检查注册中心可用性
#dubbo.consumer.check=false

# Dubbo 协议配置
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1

dubbo.provider.version=1.0.0
dubbo.provider.group=default