spring.application.name=pay-service
server.port=8082

# RocketMQ name-server
#rocketmq.name-server=namesrv-1:9876;namesrv-2:9876;namesrv-3:9876
rocketmq.name-server=192.168.5.22:9876
rocketmq.consumer.group=consumer-group

# 应用名称
dubbo.application.name=pay-service

# Zookeeper 注册中心配置 (ID为 zk)
dubbo.registries.zk.id=zk
dubbo.registries.zk.protocol=zookeeper
dubbo.registries.zk.address=192.168.2.74:2181

# Nacos 注册中心配置 (ID为 nacos)
dubbo.registries.nacos.id=nacos
dubbo.registries.nacos.protocol=nacos
dubbo.registries.nacos.address=192.168.2.74:8848

# Dubbo 协议配置
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1