spring.application.name=producer
server.port=8081

# RocketMQ name-server & producer group
rocketmq.name-server=${rocketmq.name-server:localhost:9876}
rocketmq.producer.group=${rocketmq.producer.group:producer-group}
