spring.application.name=producer
server.port=8081

# RocketMQ name-server & producer group
#rocketmq.name-server=namesrv-1:9876;namesrv-2:9876;namesrv-3:9876
rocketmq.name-server=namesrv-1:9876
rocketmq.producer.group=producer-group

# Docker Compose 生命周期管理
spring.docker.compose.lifecycle-management=start-only
# 显式指定停止时的动作为 docker compose down（彻底清理网络和容器）
#spring.docker.compose.stop.command=down
